version: '3.8'

services: 
  grafana:
    image: abes0/grafana-aa:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      GF_LOG_LEVEL: 'error'
      GF_DATAPROXY_LOGGING: 'true'
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: 'sasaki77-archiverappliance-datasource'
  
  archappl:
    hostname: archappl
    image: abes0/archiver-appliance:latest
    ports:
      - '17665:17665'
    volumes:
      - ./aa-storage/sts:/storage/sts
      - ./aa-storage/mts:/storage/mts
      - ./aa-storage/lts:/storage/lts
      - ./aa-storage/logs:/storage/logs
    stdin_open: true
    tty: true
    environment:
      ARCHAPPL_ALL_APPS_ON_ONE_JVM: 'true'
      EPICS_CA_ADDR_LIST: "psapp-test"
      EPICS_CA_AUTO_ADDR_LIST: "no"
      ARCHAPPL_PERSISTENCE_LAYER: 'org.epics.archiverappliance.config.persistence.RedisPersistence'
      ARCHAPPL_PERSISTENCE_LAYER_REDISURL: 'redis-db'
    depends_on: 
      #- mysql-db
      - redis-db
    links:
      #- mysql-db
      - redis-db
      - psapp-test
  
  #mysql-db:
  #  image: mysql
  #  volumes:
  #    - ./aa-storage:/data
  #  command: 
  
  redis-db:
    image: redis
    volumes:
      - ./redis-storage:/data
    command: redis-server --appendonly yes
  
  psapp-test:
    image: abes0/psapptest:latest
    ports:
      - '5064-5065:5064-5065/tcp'
      - '5064-5065:5064-5065/udp'
    expose:
      - '5064-5065/tcp'
      - '5064-5065/udp'
    stdin_open: true
    tty: true
    restart: always

